name:         app
version:      "0.0.1"
tested-with:  GHC==8.2.2
license-file: LICENSE.md
author:       Tomas Zemanovic <tzemanovic@gmail.com>
github:       https://github.com/tzemanovic/haskell-yesod-realworld-example-app

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

# version 1.0 had a bug in reexporting Handler, causing trouble
- classy-prelude-yesod >=0.10.2 && <1.0 || >=1.1

- QuickCheck >= 2.10 
- aeson >=0.6 && <1.5
- bytestring >=0.9 && <0.11
- case-insensitive
- classy-prelude >=0.10.2
- containers
- email-validate >= 2.3
- esqueleto >= 2.5 
- fast-logger >=2.2 && <2.5
- file-embed
- foreign-store
- forma >= 1.1
- http-types >= 0.9
- jwt >= 0.7.2 && <0.10
- monad-control >=0.3 && <1.1
- monad-logger >=0.3 && <0.4
- mtl >= 2.2
- persistent >=2.0 && <2.10
- persistent-sqlite >=2.6.2 && <2.10
- persistent-template >=2.0 && <2.8
- template-haskell
- text >=0.11 && <2.0
- unordered-containers
- wai
- wai-cors >= 0.2
- wai-extra >=3.0 && <3.1
- wai-logger >=2.2 && <2.4
- warp >=3.0 && <3.3
- yaml >=0.8 && <0.12
- yesod >=1.4.3 && <1.7
- yesod-auth >=1.4.0 && <1.7
- yesod-core >=1.4.30 && <1.7

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  app:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - app
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - app
    - hspec >=2.0.0
    - HUnit
    - yesod-test
    - microlens

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
